### ISSUE TITLE
timeout error

### ISSUE THREAD

**Issue by chandratechblog** [socool/rasa-line-connector#2]
I'm getting the output in the terminal but it is not posting to the line channel 
I'm getting timeout error 

`event---- {"message": {"id": "476039432646951332", "text": "hi", "type": "text"}, "mode": "active", "replyToken": "e697a39dc0b949a8974a4f435b8997af", "source": {"type": "user", "userId": "U2b167f879230a6b7817884a04a2217d6"}, "timestamp": 1696572916903, "type": "message"}
event--source user
user--- hi
U2b167f879230a6b7817884a04a2217d6
<addons.line_connector.LineConnectorOutput object at 0x000002363292BC10>
<rasa.core.channels.channel.UserMessage object at 0x0000023632942D00>
converted json "Hey! How are you?"
2023-10-06 12:01:00 ERROR    addons.line_connector  - Exception when trying to handle webhook for line message.
Traceback (most recent call last):
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000023612472370>, 'Connection to api.line.me timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\requests\adapters.py", line 486, in send   
    resp = conn.urlopen(
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.line.me', port=443): Max retries exceeded with url: /v2/bot/message/reply (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000023612472370>, 'Connection to api.line.me timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\rasa-line-connector-master\addons\line_connector.py", line 110, in _handle_user_message
    await self.on_new_message(user_msg)
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\rasa\core\channels\channel.py", line 89, in handler
    await app.ctx.agent.handle_message(message)
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\rasa\core\agent.py", line 419, in handle_message
    return await self.processor.handle_message(  # type: ignore[union-attr]
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\rasa\core\processor.py", line 165, in handle_message
    await self._run_prediction_loop(message.output_channel, tracker)
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\rasa\core\processor.py", line 862, in _run_prediction_loop
    should_predict_another_action = await self._run_action(
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\rasa\core\processor.py", line 995, in _run_action
    await self.execute_side_effects(events, tracker, output_channel)
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\rasa\core\processor.py", line 888, in execute_side_effects
    await self._send_bot_messages(events, tracker, output_channel)
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\rasa\core\processor.py", line 903, in _send_bot_messages
    await output_channel.send_response(tracker.sender_id, e.message())
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\rasa\core\channels\channel.py", line 233, in send_response
    await self.send_text_message(recipient_id, message.pop("text"), **message)
  File "D:\rasa-line-connector-master\addons\line_connector.py", line 168, in send_text_message
    await self.send_to_line(TextSendMessage(text= json_converted))
  File "D:\rasa-line-connector-master\addons\line_connector.py", line 147, in send_to_line
    self.line_client.reply_message(
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\linebot\api.py", line 108, in reply_message    self._post(
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\linebot\api.py", line 1242, in _post       
    response = self.http_client.post(
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\linebot\http_client.py", line 168, in post 
    response = requests.post(
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\requests\api.py", line 115, in post        
    return request("post", url, data=data, json=json, **kwargs)
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\requests\api.py", line 59, in request      
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 589, in request    resp = self.send(prep, **send_kwargs)
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 703, in send   
    r = adapter.send(request, **kwargs)
  File "c:\users\chandrasekhar.m\appdata\local\programs\python\python38\lib\site-packages\requests\adapters.py", line 507, in send   
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.line.me', port=443): Max retries exceeded with url: /v2/bot/message/reply (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000023612472370>, 'Connection to api.line.me timed out. (connect timeout=5)'))`

**Comment by socool** [comment]
did you try webhook before call api

**Comment by socool** [comment]
check your setup ngrok and line app and test using this curl command in README
```
curl --request POST \
     --url http://localhost:5005/webhooks/line/callback \
     --header 'Content-Type: application/json' \
     --data '{
            "sender": "test_user",
            "message": "Hi there!",
            "metadata": {}
          }'
```

**Comment by chandratechblog** [comment]
thanks for your reply socool
yes,  I tried the curl request it's giving 200 ok 
but still, I got the same time-out error 

`requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.line.me', port=443): Max retries exceeded with url: /v2/bot/message/reply (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001CA65E30FD0>, 'Connection to api.line.me timed out. (connect timeout=5)'))`

**Comment by socool** [comment]
I've update lib to 
- Python 3.8.17
- rasa 3.6.12
- line-bot-sdk 3.5.0
[screenshot](https://github.com/socool/rasa-line-connector/blob/master/screenshot/screenshot.png)

you neeed to run command to start ngrok and rasa action that's i've write it on README
- start ngrok
```
ngrok http 5005
```
don't forgot to verify webhook

- start rasa action
```
rasa run -m models --credentials credentials.yml --enable-api --cors "*" --debug
```
